"use client";

import { useEffect, useState } from "react";
import {
  useForm,
  FieldErrors,
  useFieldArray,
  Controller,
  useWatch,
} from "react-hook-form";
import { FormItem } from "./ui/form";
import { Label } from "./ui/label";
import { Button } from "./ui/button";
import { CustomizedInputTags } from "./ui/customized-input-tags";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "./ui/select";
import { ECFGWrapper } from "@/wasm_backend/pkg/wasm_backend";

// -------------------------------------
// 型定義
// -------------------------------------
type Production = {
  lhs: string; // 単一の文字列
  rhs: string[]; // 複数タグの配列
};

type ECFG = {
  terminals: string[];
  nonTerminals: string[];
  productions: Production[];
  startSymbol: string;
  forNullable: string[];
  forFirstSet: string[];
  forFollowSet: string;
  forDirectorSet: string;
};

export default function ECFGForm() {
  // -------------------------------------
  // useForm & State
  // -------------------------------------
  const {
    control,
    handleSubmit,
    setValue,
    formState: { errors },
  } = useForm<ECFG>({
    defaultValues: {
      terminals: [],
      nonTerminals: [],
      productions: [{ lhs: "", rhs: [] }],
      startSymbol: "",
    },
  });
  const [formData, setFormData] = useState<ECFG | null>(null);

  // -------------------------------------
  // Field Array: productions
  // -------------------------------------
  const { fields, append, remove } = useFieldArray({
    name: "productions",
    control,
  });

  // -------------------------------------
  // useWatchをコンポーネントのトップレベルで呼び出す
  // -------------------------------------
  const productions = useWatch({ control, name: "productions" });
  const nonTerminals = useWatch({ control, name: "nonTerminals" }) || [];

  // -------------------------------------
  // productions が変化するたび、NonTerminals & Terminals を再計算
  // -------------------------------------
  useEffect(() => {
    if (!productions) return;

    // === NonTerminals: 全LHS を収集 ===
    const lhsSet = new Set<string>();
    productions.forEach((prod) => {
      if (prod.lhs) {
        lhsSet.add(prod.lhs);
      }
    });
    setValue("nonTerminals", Array.from(lhsSet));

    // === Terminals: 全シンボル( LHS + RHS ) から NonTerminals + 特殊記号 を除外
    const specialTokens = new Set(["\\{", "\\}", "\\|", "\\(", "\\)"]);
    const allSymbols = new Set<string>();
    productions.forEach((prod) => {
      // LHS
      if (prod.lhs) {
        allSymbols.add(prod.lhs);
      }
      // RHS
      prod.rhs.forEach((sym) => {
        allSymbols.add(sym);
      });
    });

    // 除外
    for (const nt of lhsSet) {
      allSymbols.delete(nt);
    }
    for (const st of specialTokens) {
      allSymbols.delete(st);
    }
    setValue("terminals", Array.from(allSymbols));
  }, [productions, setValue]);

  // -------------------------------------
  // Submit handlers
  // -------------------------------------
  const onValid = (data: ECFG) => {
    setFormData(data);
    const ecfg = new ECFGWrapper(
      data.terminals,
      data.nonTerminals,
      data.productions,
      data.startSymbol,
    );
    console.log("ell1 かな？: ", ecfg.is_ell1());
    console.log("Form data:", data);
  };
  const onInvalid = (errors: FieldErrors<ECFG>) => {
    console.error("Validation errors:", errors);
  };

  // -------------------------------------
  // Render
  // -------------------------------------
  return (
    <form onSubmit={handleSubmit(onValid, onInvalid)} className="space-y-3">
      {/* 1) NonTerminal symbols (自動生成 & 編集不可) */}
      <FormItem>
        <Label>NonTerminal symbols (auto-generated by productions)</Label>
        <Controller
          name="nonTerminals"
          control={control}
          render={({ field }) => (
            <CustomizedInputTags
              {...field}
              value={field.value}
              disabled
              onChange={() => {
                // 手動編集不可
              }}
            />
          )}
        />
      </FormItem>

      {/* 2) Terminal symbols (自動生成 & 編集不可) */}
      <FormItem>
        <Label>Terminal symbols (auto-generated by productions)</Label>
        <Controller
          name="terminals"
          control={control}
          render={({ field }) => (
            <CustomizedInputTags
              {...field}
              value={field.value}
              disabled
              onChange={() => {
                // 手動編集不可
              }}
            />
          )}
        />
      </FormItem>

      {/* 3) productions (手動編集) */}
      <FormItem>
        <Label>Productions</Label>
        {errors.productions && (
          <span className="px-2 text-sm text-red-500">
            {"The symbol in LHS must not be empty."}
          </span>
        )}
        {fields.map((fieldItem, index) => (
          <div key={fieldItem.id} className="mb-4 flex items-center gap-2">
            {/* LHS (単一タグ) */}
            <div>
              {errors.productions && errors.productions[index]?.lhs && (
                <span className="px-2 text-sm text-red-500">{"*"}</span>
              )}
            </div>
            <div className="flex-1" style={{ flexBasis: "15%" }}>
              <Controller
                name={`productions.${index}.lhs`}
                rules={{
                  required: "The symbol in LHS must not be empty.",
                }}
                control={control}
                render={({ field }) => (
                  <CustomizedInputTags
                    maxTags={1}
                    {...field}
                    // LHS は単一タグなので配列にして渡す
                    value={field.value ? [field.value] : []}
                    onChange={(newValue) => {
                      // もし newValue が関数の場合は1文字列だけにする
                      if (typeof newValue === "function") {
                        field.onChange("");
                      } else {
                        field.onChange(newValue[0] || "");
                      }
                    }}
                  />
                )}
              />
            </div>

            <span className="font-bold">→</span>

            {/* RHS (複数タグ) */}
            <div className="flex-1" style={{ flexBasis: "75%" }}>
              <Controller
                name={`productions.${index}.rhs`}
                control={control}
                render={({ field }) => (
                  <CustomizedInputTags
                    {...field}
                    value={field.value}
                    onChange={(newValue) => {
                      if (typeof newValue === "function") {
                        field.onChange([]);
                      } else {
                        field.onChange(newValue);
                      }
                    }}
                  />
                )}
              />
            </div>

            <Button
              type="button"
              onClick={() => remove(index)}
              className="bg-red-500 text-white"
            >
              Remove
            </Button>
          </div>
        ))}

        <div>
          <Button
            type="button"
            onClick={() => append({ lhs: "", rhs: [] })}
            className="mt-4 bg-green-500 text-white"
          >
            Add Production
          </Button>
        </div>
      </FormItem>

      {/* 4) Start symbol (NonTerminals から選択) */}
      <FormItem>
        <Label>Start symbol</Label>
        {errors.startSymbol && (
          <span className="px-2 text-sm text-red-500">
            {errors.startSymbol.message}
          </span>
        )}
        <Controller
          name="startSymbol"
          rules={{
            required: "Start symbol is required.",
          }}
          control={control}
          render={({ field }) => (
            <Select
              value={field.value} // フォームの値を反映
              onValueChange={(value) => field.onChange(value)} // 値が変更されたときにフォームの状態を更新
            >
              <SelectTrigger className="w-[180px]">
                <SelectValue placeholder="Choose NonTerminal" />
              </SelectTrigger>
              <SelectContent>
                {nonTerminals.map((nt) => (
                  <SelectItem key={nt} value={nt}>
                    {nt}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          )}
        />
      </FormItem>

      <button
        type="submit"
        className="mt-4 rounded bg-blue-500 px-4 py-2 text-white"
      >
        Submit
      </button>

      {formData && (
        <pre className="mt-4 rounded border p-2">
          {JSON.stringify(formData, null, 2)}
        </pre>
      )}
    </form>
  );
}
